name: i_travel_book
description: A new Flutter project.

version: 1.0.0+2

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  animated_splash_screen: ^1.2.0
  auto_size_text: ^3.0.0
  cloud_firestore: ^3.1.8
  device_preview: ^1.1.0
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_launcher_icons: ^0.9.2
  geocoding: ^2.0.2
  geolocator: ^8.1.1
  google_fonts: ^2.3.1
  google_maps_flutter: ^2.1.4
  google_mobile_ads: ^1.1.0
  google_sign_in: ^5.3.0
  image_picker: ^0.8.5
  internet_connection_checker: ^0.0.1+3
  kartal: ^2.3.1
  lottie: ^1.2.2
  shared_preferences: ^2.0.13
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
